/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters
// ignore_for_file: invalid_use_of_internal_member

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _ida;
import 'package:http/http.dart' as _i85jenna;
import 'package:puls3_client/src/protocol/agent/agent_summary.dart'
    as _i78wn19p;
import 'package:puls3_client/src/protocol/auth/wallet_challenge.dart'
    as _ig3t6cu4;
import 'package:puls3_client/src/protocol/create_hire_result.dart' as _iyigzt6l;
import 'package:puls3_client/src/protocol/greetings/greeting.dart' as _igee0kk1;
import 'package:puls3_client/src/protocol/health/backend_health.dart'
    as _iur07860;
import 'package:puls3_client/src/protocol/hire_detail.dart' as _iytku71p;
import 'package:puls3_client/src/protocol/prepared_transaction.dart'
    as _iy6q6dct;
import 'package:serverpod_auth_core_client/serverpod_auth_core_client.dart'
    as _iacc;
import 'package:serverpod_auth_idp_client/serverpod_auth_idp_client.dart'
    as _iaic;
import 'package:serverpod_client/serverpod_client.dart' as _isc;
import 'protocol.dart' as _il2as5qe;

/// Serves the agent catalog from the Postgres index, with an on-chain
/// fallback while the index is empty.
///
/// The endpoint depends only on [CatalogReader]; every chain detail lives in
/// [buildAgentCatalogReader] and the services behind it. When the chain is
/// unreachable and nothing is indexed, `list` and `get` may throw
/// [AgentCatalogUnavailable] through the fallback instead of answering with
/// an empty catalog.
/// {@category Endpoint}
class EndpointAgent extends _isc.EndpointRef {
  EndpointAgent(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'agent';

  /// Every agent in the catalog, ordered by registry id.
  _ida.Future<List<_i78wn19p.AgentSummary>> list() =>
      caller.callServerEndpoint<List<_i78wn19p.AgentSummary>>(
        'agent',
        'list',
        {},
      );

  /// The agent with metadata id [id], or `null` when there is none.
  _ida.Future<_i78wn19p.AgentSummary?> get(String id) =>
      caller.callServerEndpoint<_i78wn19p.AgentSummary?>(
        'agent',
        'get',
        {'id': id},
      );
}

/// By extending [RefreshJwtTokensEndpoint], the JWT token refresh endpoint
/// is made available on the server and enables automatic token refresh on the client.
/// {@category Endpoint}
class EndpointJwtRefresh extends _iacc.EndpointRefreshJwtTokens {
  EndpointJwtRefresh(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'jwtRefresh';

  /// Creates a new token pair for the given [refreshToken].
  ///
  /// If [refreshToken] is omitted, cookie-mode web clients fall back to the
  /// configured HttpOnly refresh cookie. When neither source is present this
  /// throws [RefreshTokenNotFoundException], the same public "no usable refresh
  /// credential" exception used for unknown refresh tokens.
  ///
  /// Can throw the following exceptions:
  /// -[RefreshTokenMalformedException]: refresh token is malformed and could
  ///   not be parsed. Not expected to happen for tokens issued by the server.
  /// -[RefreshTokenNotFoundException]: refresh token is unknown to the server.
  ///   Either the token was deleted or generated by a different server.
  /// -[RefreshTokenExpiredException]: refresh token has expired. Will happen
  ///   only if it has not been used within configured `refreshTokenLifetime`.
  /// -[RefreshTokenInvalidSecretException]: refresh token is incorrect, meaning
  ///   it does not refer to the current secret refresh token. This indicates
  ///   either a malfunctioning client or a malicious attempt by someone who has
  ///   obtained the refresh token. In this case the underlying refresh token
  ///   will be deleted, and access to it will expire fully when the last access
  ///   token is elapsed.
  ///
  /// This endpoint is unauthenticated, meaning the client won't include any
  /// authentication information with the call.
  @override
  _ida.Future<_iacc.AuthSuccess> refreshAccessToken({String? refreshToken}) =>
      caller.callServerEndpoint<_iacc.AuthSuccess>(
        'jwtRefresh',
        'refreshAccessToken',
        {'refreshToken': refreshToken},
        authenticated: false,
      );
}

/// SEP-10 wallet sign-in (`client.walletAuth`).
///
/// Both calls are open so a signed-out client can start, and a client that
/// already holds a session can still challenge a different wallet.
/// {@category Endpoint}
class EndpointWalletAuth extends _isc.EndpointRef {
  EndpointWalletAuth(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'walletAuth';

  /// A single-use challenge for [wallet].
  _ida.Future<_ig3t6cu4.WalletChallenge> createChallenge(String wallet) =>
      caller.callServerEndpoint<_ig3t6cu4.WalletChallenge>(
        'walletAuth',
        'createChallenge',
        {'wallet': wallet},
        authenticated: false,
      );

  /// A session for the wallet that signed [signedChallengeXdr].
  _ida.Future<_iacc.AuthSuccess> verifyChallenge(
    String challengeId,
    String wallet,
    String signedChallengeXdr,
  ) => caller.callServerEndpoint<_iacc.AuthSuccess>(
    'walletAuth',
    'verifyChallenge',
    {
      'challengeId': challengeId,
      'wallet': wallet,
      'signedChallengeXdr': signedChallengeXdr,
    },
    authenticated: false,
  );
}

/// This is an example endpoint that returns a greeting message through
/// its [hello] method.
/// {@category Endpoint}
class EndpointGreeting extends _isc.EndpointRef {
  EndpointGreeting(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'greeting';

  /// Returns a personalized greeting message: "Hello {name}".
  _ida.Future<_igee0kk1.Greeting> hello(String name) =>
      caller.callServerEndpoint<_igee0kk1.Greeting>(
        'greeting',
        'hello',
        {'name': name},
      );
}

/// Reports whether the backend is reachable and which app version it runs.
/// {@category Endpoint}
class EndpointHealth extends _isc.EndpointRef {
  EndpointHealth(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'health';

  /// Returns basic health information without requiring authentication.
  _ida.Future<_iur07860.BackendHealth> check() =>
      caller.callServerEndpoint<_iur07860.BackendHealth>(
        'health',
        'check',
        {},
      );
}

/// Creates hires and relays their escrow calls (api.md, `HireEndpoint`).
///
/// Every method first resolves the caller through [SessionWallet.requireLogin]
/// and only then builds the services, so a caller without a session reaches no
/// store and no chain. Wallet parameters must equal the session wallet
/// (`WalletMismatch`), and ownership of a hire is checked against the session
/// wallet by the services.
///
/// `getHire` and `listHires` are not part of this endpoint yet.
///
/// Follow-ups: `InputTooLong` has no documented limit, so the input length is
/// not checked here; `PersistenceUnavailable` is not mapped, so a database
/// failure surfaces as Serverpod's own internal error.
/// {@category Endpoint}
class EndpointHire extends _isc.EndpointRef {
  EndpointHire(_isc.EndpointCaller caller) : super(caller);

  @override
  String get name => 'hire';

  /// Creates the hire of [requestId] for [consumer] and prepares its
  /// `create_job`; repeating the request returns the same hire.
  _ida.Future<_iyigzt6l.CreateHireResult> createHire(
    int agentId,
    String consumer,
    String input,
    String requestId,
  ) => caller.callServerEndpoint<_iyigzt6l.CreateHireResult>(
    'hire',
    'createHire',
    {
      'agentId': agentId,
      'consumer': consumer,
      'input': input,
      'requestId': requestId,
    },
  );

  /// A fresh unsigned `create_job` for a hire that has no job yet.
  _ida.Future<_iy6q6dct.PreparedTransaction> prepareCreateJob(int hireId) =>
      caller.callServerEndpoint<_iy6q6dct.PreparedTransaction>(
        'hire',
        'prepareCreateJob',
        {'hireId': hireId},
      );

  /// The unsigned `fund` of an open hire.
  _ida.Future<_iy6q6dct.PreparedTransaction> prepareFund(int hireId) =>
      caller.callServerEndpoint<_iy6q6dct.PreparedTransaction>(
        'hire',
        'prepareFund',
        {'hireId': hireId},
      );

  /// The unsigned `complete` of a submitted hire.
  _ida.Future<_iy6q6dct.PreparedTransaction> prepareComplete(int hireId) =>
      caller.callServerEndpoint<_iy6q6dct.PreparedTransaction>(
        'hire',
        'prepareComplete',
        {'hireId': hireId},
      );

  /// The unsigned `reject` of a hire, with the consumer's [reason].
  _ida.Future<_iy6q6dct.PreparedTransaction> prepareReject(
    int hireId,
    String reason,
  ) => caller.callServerEndpoint<_iy6q6dct.PreparedTransaction>(
    'hire',
    'prepareReject',
    {
      'hireId': hireId,
      'reason': reason,
    },
  );

  /// Verifies the wallet-signed envelope of [preparationId] and relays it.
  _ida.Future<_iytku71p.HireDetail> submitEscrowCall(
    int hireId,
    String preparationId,
    String signedTransactionXdr,
  ) => caller.callServerEndpoint<_iytku71p.HireDetail>(
    'hire',
    'submitEscrowCall',
    {
      'hireId': hireId,
      'preparationId': preparationId,
      'signedTransactionXdr': signedTransactionXdr,
    },
  );
}

class Modules {
  Modules(Client client) {
    serverpod_auth_idp = _iaic.Caller(client);
    serverpod_auth_core = _iacc.Caller(client);
  }

  late final _iaic.Caller serverpod_auth_idp;

  late final _iacc.Caller serverpod_auth_core;
}

class Client extends _isc.ServerpodClientShared {
  Client(
    String host, {
    dynamic securityContext,
    Duration? streamingConnectionTimeout,
    Duration? connectionTimeout,
    Function(
      _isc.MethodCallContext,
      Object,
      StackTrace,
    )?
    onFailedCall,
    Function(_isc.MethodCallContext)? onSucceededCall,
    bool? disconnectStreamsOnLostInternetConnection,
    _i85jenna.Client? httpClientOverride,
  }) : super(
         host,
         _il2as5qe.Protocol(),
         securityContext: securityContext,
         streamingConnectionTimeout: streamingConnectionTimeout,
         connectionTimeout: connectionTimeout,
         onFailedCall: onFailedCall,
         onSucceededCall: onSucceededCall,
         disconnectStreamsOnLostInternetConnection:
             disconnectStreamsOnLostInternetConnection,
         httpClientOverride: httpClientOverride,
       ) {
    agent = EndpointAgent(this);
    jwtRefresh = EndpointJwtRefresh(this);
    walletAuth = EndpointWalletAuth(this);
    greeting = EndpointGreeting(this);
    health = EndpointHealth(this);
    hire = EndpointHire(this);
    modules = Modules(this);
  }

  late final EndpointAgent agent;

  late final EndpointJwtRefresh jwtRefresh;

  late final EndpointWalletAuth walletAuth;

  late final EndpointGreeting greeting;

  late final EndpointHealth health;

  late final EndpointHire hire;

  late final Modules modules;

  @override
  Map<String, _isc.EndpointRef> get endpointRefLookup => {
    'agent': agent,
    'jwtRefresh': jwtRefresh,
    'walletAuth': walletAuth,
    'greeting': greeting,
    'health': health,
    'hire': hire,
  };

  @override
  Map<String, _isc.ModuleEndpointCaller> get moduleLookup => {
    'serverpod_auth_idp': modules.serverpod_auth_idp,
    'serverpod_auth_core': modules.serverpod_auth_core,
  };
}
